### ISSUE TITLE
`-V` does not work

### ISSUE THREAD

**Issue by scop** [junk1tm/musttag#13]
With current `@latest`

```shellsession
$ musttag --help 2>&1 | grep -- -V
  -V	print version and exit
$ musttag -V
musttag: unsupported flag value: -V=true
```

**Comment by junk1tm** [comment]
Looks like the builtin `go/analysis` implementation of the `-V` flag only accepts the `full` value 🤔

```go
if s != "full" {
	log.Fatalf("unsupported flag value: -V=%s", s)
}
```

Moreover, it prints the hash of the binary, not some readable version, which is probably not what we want. Anyway, I can see that the flag can be reassigned, so I'm gonna put the current semver tag in it.
