### ISSUE TITLE
false-positive: elements outside of the module are reported

### ISSUE THREAD

**Issue by ldez** [junk1tm/musttag#17]
musttag: v0.4.4
golangci-lint: v1.51.1

```go
package main

import (
	"encoding/json"

	"github.com/stripe/stripe-go/v74"
)

func main() {
	var payload []byte

	var event stripe.Event
	if err := json.Unmarshal(payload, &event); err != nil {
		return
	}
}
```

```go
module github.com/example/sandbox

go 1.19

require github.com/stripe/stripe-go/v74 v74.7.0
```

```console
$ golangci-lint run -Emusttag
../../../../pkg/mod/github.com/stripe/stripe-go/v74@v74.7.0/stripe.go:151:6: exported fields should be annotated with the "json" tag (musttag)
type APIResource struct {
     ^
```

1. The element is outside of the module
2. It's an embedded field

https://github.com/stripe/stripe-go/blob/615945288142b0b41e502cd4b82f9e74c168ad8d/event.go#L86-L107

**Comment by junk1tm** [comment]
Thank you, I'm currently investigating this one. I'll let you know when the fix is ready.

**Comment by junk1tm** [comment]
Incorrect report position has been fixed in #18 (in the above example the `APIResponse` type should have been reported, not `APIResource`).

Reporting elements outside of the current module will be disabled in a separate PR.

**Comment by ldez** [comment]
Sorry but the problem is still here:

```
$ golangci-lint version      
golangci-lint has version 1.51.2 built from 3e8facb4 on 2023-02-19T21:43:54Z

$ go version -m $(which golangci-lint) | grep musttag
sandbox dep masgithub.com/junk1tm/musttag      v0.4.5  h1:d+mpJ1vn6WFEVKHwkgJiIedis1u/EawKOuUTygAUtCo=

$ golangci-lint run -Emusttag
../../../../pkg/mod/github.com/stripe/stripe-go/v74@v74.7.0/stripe.go:89:1: exported fields should be annotated with the "json" tag (musttag)
type APIResponse struct {
^
```

**Comment by ldez** [comment]
I didn't see that the commit was after the release

**Comment by junk1tm** [comment]
@ldez Yes, currently the fix is only available in the main branch (I've been testing it on various codebases to make sure it doesn't produce new errors).

I'm going to push a few small improvements and then publish a new release with this fix included.

If I need to update some tests for `musttag` in `golangci-lint`, can I somehow do it in the dependabot's PR or do you want me to create a separate one? Thank you.

**Comment by ldez** [comment]
Thank you for your reactivity :+1: 

As you are the linter author and it's a special context, you can create a PR to update your linter and update the golangci-lint code accordingly (no need to wait for the dependabot).
